<?php
// Seed 10 sample blog posts into the database
require_once __DIR__ . '/api/db.php';

$posts = [
    [
        'title' => 'Understanding the Closed Die Forging Process',
        'slug' => 'understanding-closed-die-forging-process',
        'excerpt' => 'Closed die forging is one of the most precise metal forming methods used in modern manufacturing. Learn how this process creates high-strength components for automotive, aerospace, and industrial applications.',
        'author' => 'JK Forge Team',
        'content' => '<h2>What is Closed Die Forging?</h2><p>Closed die forging, also known as impression die forging, is a metal forming process where heated metal is placed between two dies that contain an impression of the desired shape. When the dies come together under tremendous pressure, the metal flows and fills the die cavity, creating a precisely shaped component.</p><h2>Key Advantages</h2><ul><li><strong>Superior Strength:</strong> The grain structure of the metal follows the shape of the part, providing unmatched mechanical properties.</li><li><strong>Dimensional Accuracy:</strong> Tight tolerances can be achieved, reducing the need for secondary machining.</li><li><strong>Material Efficiency:</strong> Less waste compared to machining from solid blocks.</li><li><strong>Repeatability:</strong> Once tooling is created, thousands of identical parts can be produced.</li></ul><h2>Applications</h2><p>Closed die forging is widely used in the automotive industry for manufacturing crankshafts, connecting rods, steering knuckles, and gear blanks. In the oil and gas sector, it produces valve bodies, flanges, and fittings that must withstand extreme pressures and temperatures.</p><blockquote>At JK Forge, we operate state-of-the-art closed die forging presses ranging from 1000 to 16000 tons, capable of producing components weighing from 0.5 kg to 150 kg.</blockquote><h2>Our Process</h2><p>Our closed die forging process begins with careful die design using advanced CAD/CAM software. We select the optimal billet size, heating temperature, and forging sequence to ensure the highest quality output. Every forged component undergoes rigorous quality inspection including dimensional checks, hardness testing, and ultrasonic examination.</p>'
    ],
    [
        'title' => 'How Forged Components Outperform Cast Parts in Automotive Applications',
        'slug' => 'forged-vs-cast-automotive-components',
        'excerpt' => 'When it comes to critical automotive components, forged parts consistently outperform their cast counterparts. Discover the key differences and why leading OEMs prefer forged components.',
        'author' => 'JK Forge Team',
        'content' => '<h2>The Forging vs. Casting Debate</h2><p>Both forging and casting are fundamental metal forming processes, but they produce components with significantly different properties. Understanding these differences is crucial for engineers selecting the right manufacturing method for their application.</p><h2>Mechanical Properties Comparison</h2><p>Forged components exhibit superior mechanical properties due to the controlled deformation of the metal\'s grain structure. During forging, the grain flow is aligned with the shape of the part, resulting in:</p><ul><li><strong>30-50% higher fatigue strength</strong> compared to cast parts</li><li><strong>Greater impact resistance</strong> for safety-critical applications</li><li><strong>Better ductility</strong> allowing the component to absorb energy before failure</li><li><strong>Consistent microstructure</strong> free from porosity and shrinkage defects</li></ul><h2>Real-World Performance</h2><p>In automotive applications, this translates to longer service life, better safety margins, and reduced warranty claims. Components like suspension arms, steering knuckles, and crankshafts benefit enormously from the forging process.</p><h3>Case Study: Connecting Rods</h3><p>A forged connecting rod can withstand millions of fatigue cycles at engine speeds exceeding 6000 RPM, while a comparable cast rod would typically fail much sooner under the same conditions. This is why performance and commercial vehicle engines universally use forged connecting rods.</p><h2>Cost Considerations</h2><p>While the initial tooling cost for forging is higher than casting, the total cost of ownership is often lower when you factor in reduced failure rates, longer service intervals, and the ability to use lighter designs that still meet strength requirements.</p>'
    ],
    [
        'title' => 'The Role of Heat Treatment in Forged Steel Components',
        'slug' => 'heat-treatment-forged-steel-components',
        'excerpt' => 'Heat treatment is a critical step that determines the final properties of forged steel parts. Explore the different heat treatment processes and how they enhance component performance.',
        'author' => 'JK Forge Team',
        'content' => '<h2>Why Heat Treatment Matters</h2><p>After forging, steel components undergo heat treatment to achieve the desired combination of hardness, strength, and toughness. Without proper heat treatment, even the best forging process cannot deliver optimal performance.</p><h2>Common Heat Treatment Processes</h2><h3>1. Normalizing</h3><p>Normalizing involves heating the forged part above its critical temperature and then air cooling. This refines the grain structure and relieves internal stresses from the forging process, producing a uniform microstructure throughout the component.</p><h3>2. Quenching and Tempering</h3><p>This two-step process first involves rapidly cooling (quenching) the heated component in oil or water to achieve maximum hardness. The part is then tempered at a lower temperature to achieve the desired balance of hardness and toughness. This is the most common treatment for high-strength automotive and industrial components.</p><h3>3. Case Hardening (Carburizing)</h3><p>For components that need a hard, wear-resistant surface with a tough core — such as gears and bearings — case hardening introduces carbon into the surface layer at high temperatures. This creates a hard outer shell while maintaining a ductile core.</p><h3>4. Induction Hardening</h3><p>Selective hardening of specific areas using electromagnetic induction. Ideal for components like crankshaft journals and gear teeth where only certain surfaces need enhanced hardness.</p><h2>Quality Control</h2><p>At JK Forge, every heat-treated component is tested for hardness (Rockwell/Brinell), microstructure (metallographic examination), and dimensional stability. We maintain detailed records of all heat treatment parameters for full traceability.</p>'
    ],
    [
        'title' => 'Forging Solutions for the Oil and Gas Industry',
        'slug' => 'forging-solutions-oil-gas-industry',
        'excerpt' => 'The oil and gas industry demands components that can withstand extreme pressures, temperatures, and corrosive environments. Learn how precision forging meets these challenging requirements.',
        'author' => 'JK Forge Team',
        'content' => '<h2>Extreme Demands, Engineered Solutions</h2><p>The oil and gas industry operates in some of the most demanding environments on earth. From deep-sea drilling platforms to high-pressure refinery equipment, every component must perform flawlessly under extreme conditions.</p><h2>Critical Forged Components</h2><ul><li><strong>Valve Bodies & Bonnets:</strong> Forged from ASTM A105, A182 grade steels to withstand pressures exceeding 15,000 PSI</li><li><strong>Flanges:</strong> Weld neck, blind, and slip-on flanges in sizes from 1" to 60" diameter</li><li><strong>Fittings:</strong> Elbows, tees, reducers, and couplings for high-pressure piping systems</li><li><strong>Drilling Components:</strong> Stabilizers, crossovers, and subs that endure severe downhole conditions</li></ul><h2>Material Selection</h2><p>We work with a wide range of materials specifically suited for oil and gas applications:</p><ul><li>Carbon Steel (AISI 1045, 4140, 4340)</li><li>Alloy Steel (F11, F22, F91)</li><li>Stainless Steel (304, 316, 410, Duplex)</li><li>Nickel Alloys (Inconel, Monel) for extreme corrosion resistance</li></ul><blockquote>Every forged component for oil and gas applications undergoes 100% non-destructive testing including ultrasonic, magnetic particle, and liquid penetrant inspection per ASME and API standards.</blockquote><h2>Certifications</h2><p>JK Forge maintains ISO 9001:2015 certification and follows API, ASME, and NACE standards for all oil and gas components. Full material test reports and certificates of conformance are provided with every shipment.</p>'
    ],
    [
        'title' => 'Innovations in Agricultural Equipment Forging',
        'slug' => 'innovations-agricultural-equipment-forging',
        'excerpt' => 'Modern farming equipment demands durable, high-performance forged components. Discover how advanced forging techniques are revolutionizing agricultural machinery manufacturing.',
        'author' => 'JK Forge Team',
        'content' => '<h2>Forging for Modern Agriculture</h2><p>Agricultural equipment operates under harsh conditions — abrasive soils, heavy loads, continuous vibration, and exposure to the elements. Forged components are the backbone of reliable farm machinery, from tractors to harvesters to tillage equipment.</p><h2>Key Agricultural Forged Parts</h2><ul><li><strong>Tractor Components:</strong> Front axle beams, steering arms, connecting rods, and crankshafts</li><li><strong>Tillage Tools:</strong> Cultivator shovels, plough shares, and disc blades</li><li><strong>Harvester Parts:</strong> Knife guards, sickle sections, and drive components</li><li><strong>Implement Parts:</strong> Hydraulic cylinder rods, linkage arms, and PTO shafts</li></ul><h2>Design for Durability</h2><p>Agricultural components face unique challenges: they must be strong enough to handle peak loads while remaining cost-effective for a price-sensitive market. Our engineering team works closely with OEMs to optimize designs that maximize strength-to-weight ratios while minimizing material usage.</p><h3>Advanced Simulation</h3><p>Using Finite Element Analysis (FEA) and forging simulation software, we can predict material flow, identify potential defects, and optimize die designs before cutting any steel. This reduces development time and ensures first-article success.</p><h2>Surface Treatments</h2><p>For agricultural applications, we offer specialized surface treatments including zinc plating, black oxide coating, and powder coating to protect against corrosion and extend component life in the field.</p>'
    ],
    [
        'title' => 'Quality Control in Precision Forging: Our Testing Standards',
        'slug' => 'quality-control-precision-forging-testing',
        'excerpt' => 'Quality is not negotiable in precision forging. Explore the comprehensive testing and inspection methods JK Forge employs to ensure every component meets the highest standards.',
        'author' => 'JK Forge Team',
        'content' => '<h2>Our Commitment to Quality</h2><p>At JK Forge, quality is built into every step of the manufacturing process — from raw material selection through final inspection. Our quality management system is designed to prevent defects, not just detect them.</p><h2>Incoming Material Inspection</h2><p>Every batch of raw material is tested upon receipt:</p><ul><li>Chemical composition analysis using Optical Emission Spectrometry (OES)</li><li>Hardness testing to verify material grade</li><li>Visual inspection for surface defects</li><li>Dimensional verification of bar stock</li></ul><h2>In-Process Controls</h2><p>During forging, we monitor critical parameters in real-time:</p><ul><li>Billet temperature using infrared pyrometers (±10°C accuracy)</li><li>Press tonnage and stroke monitoring</li><li>Die temperature management</li><li>First-piece inspection at every setup change</li></ul><h2>Final Inspection Methods</h2><h3>Dimensional Inspection</h3><p>CMM (Coordinate Measuring Machine) inspection for critical dimensions with accuracy to 0.001mm. Statistical Process Control (SPC) charts track key characteristics across production runs.</p><h3>Non-Destructive Testing</h3><ul><li><strong>Ultrasonic Testing:</strong> Detects internal flaws, inclusions, and forging laps</li><li><strong>Magnetic Particle Inspection:</strong> Identifies surface and near-surface cracks</li><li><strong>Hardness Testing:</strong> Brinell and Rockwell testing at multiple locations per part</li></ul><h3>Destructive Testing</h3><p>Periodic sample testing includes tensile testing, impact testing (Charpy V-notch), and metallographic examination to verify microstructure and grain flow.</p>'
    ],
    [
        'title' => 'The Future of Green Manufacturing in the Forging Industry',
        'slug' => 'future-green-manufacturing-forging-industry',
        'excerpt' => 'Sustainability is reshaping the forging industry. Learn about the eco-friendly practices and technologies that are reducing the environmental footprint of metal forging operations.',
        'author' => 'JK Forge Team',
        'content' => '<h2>Forging a Sustainable Future</h2><p>The manufacturing industry faces increasing pressure to reduce its environmental impact. The forging sector is responding with innovative approaches that reduce energy consumption, minimize waste, and lower carbon emissions without compromising product quality.</p><h2>Energy Efficiency Initiatives</h2><ul><li><strong>Regenerative Furnaces:</strong> Modern heating systems that recover waste heat to preheat incoming billets, reducing energy consumption by up to 40%</li><li><strong>Servo-Driven Presses:</strong> Energy-efficient presses that consume power only during the actual forging stroke, unlike traditional flywheel presses</li><li><strong>LED Lighting & Smart Controls:</strong> Plant-wide energy management systems that optimize power consumption</li></ul><h2>Material Waste Reduction</h2><p>Forging is inherently more material-efficient than subtractive manufacturing methods like machining. However, we continue to push the boundaries:</p><ul><li>Near-net-shape forging designs that minimize flash and reduce machining allowances</li><li>100% recycling of forging flash and scrap back into the steel supply chain</li><li>Optimized billet sizing through simulation to reduce material waste</li></ul><h2>Water and Emissions</h2><p>Closed-loop water cooling systems eliminate water waste from die cooling operations. Advanced fume extraction and filtration systems ensure compliance with air quality standards while protecting worker health.</p><blockquote>By 2030, JK Forge aims to reduce its carbon footprint by 35% through a combination of renewable energy adoption, process optimization, and sustainable supply chain practices.</blockquote>'
    ],
    [
        'title' => 'Mining Industry: Why Forged Components Are Essential',
        'slug' => 'mining-industry-forged-components-essential',
        'excerpt' => 'Mining operations demand extreme durability from every component. Discover why forged parts are the preferred choice for crushing, conveying, and excavation equipment.',
        'author' => 'JK Forge Team',
        'content' => '<h2>Built for the Toughest Conditions</h2><p>Mining is one of the most demanding applications for mechanical components. Equipment operates 24/7 under massive loads, severe impacts, and abrasive conditions. Component failure means costly downtime and safety risks. That\'s why mining equipment manufacturers specify forged components for critical applications.</p><h2>Mining Forged Components</h2><ul><li><strong>Crusher Parts:</strong> Jaw crusher toggle plates, eccentric shafts, and pitman arms</li><li><strong>Conveyor Components:</strong> Drive shafts, sprockets, and coupling halves</li><li><strong>Excavator Parts:</strong> Bucket teeth, link pins, and track shoes</li><li><strong>Drilling Equipment:</strong> Drill bits, rod couplings, and stabilizers</li></ul><h2>Material Selection for Mining</h2><p>Mining components require careful material selection to balance wear resistance, impact toughness, and cost:</p><ul><li><strong>Manganese Steel (Hadfield):</strong> For extreme impact and abrasion resistance in crusher components</li><li><strong>4340 Alloy Steel:</strong> Quenched and tempered for high-strength structural components</li><li><strong>Boron Steel:</strong> Cost-effective alternative for wear-resistant ground engaging tools</li></ul><h2>Extended Service Life</h2><p>Forged mining components typically last 2-3 times longer than cast alternatives in high-impact applications. The aligned grain structure resists crack propagation, meaning forged components deform rather than fracture under overload conditions — a critical safety advantage in mining operations.</p>'
    ],
    [
        'title' => 'Understanding Hydraulic Fittings: Types, Standards, and Applications',
        'slug' => 'understanding-hydraulic-fittings-types-standards',
        'excerpt' => 'Hydraulic fittings are critical components in fluid power systems across industries. This guide covers the major types, material standards, and selection criteria for hydraulic fittings.',
        'author' => 'JK Forge Team',
        'content' => '<h2>The Backbone of Hydraulic Systems</h2><p>Hydraulic fittings connect hoses, tubes, and pipes in fluid power systems operating at pressures from 500 to over 10,000 PSI. The reliability of these connections is paramount — a single fitting failure can cause equipment downtime, environmental contamination, and safety hazards.</p><h2>Major Types of Hydraulic Fittings</h2><h3>1. JIC (Joint Industry Council) Fittings</h3><p>The most widely used hydraulic fitting style, featuring a 37° flare seat. JIC fittings provide excellent sealing and can be assembled and disassembled repeatedly without degradation. Common in mobile and industrial hydraulic systems.</p><h3>2. BSP (British Standard Pipe) Fittings</h3><p>Used extensively in European and Asian markets, available in both parallel (BSPP) and tapered (BSPT) thread forms. BSPP fittings use a bonded seal or O-ring for sealing, while BSPT relies on thread interference.</p><h3>3. SAE O-Ring Boss (ORB) Fittings</h3><p>Feature an O-ring in a machined groove on the male fitting that seals against a flat surface on the female port. Provides a leak-free connection ideal for high-pressure applications.</p><h3>4. Metric Fittings (DIN)</h3><p>Following DIN 2353 standards, these fittings use a 24° cone with an O-ring seal. Increasingly popular as global equipment manufacturers standardize on metric threads.</p><h2>Material Standards</h2><p>Forged hydraulic fittings are manufactured from:</p><ul><li>Carbon Steel (SAE 1215, 12L14) — most common, zinc plated for corrosion protection</li><li>Stainless Steel (316SS) — for corrosive environments and food-grade applications</li><li>Brass — for low-pressure pneumatic systems</li></ul><h2>Forging Advantage</h2><p>Forged fittings offer superior pressure ratings and burst strength compared to machined-from-bar fittings due to the grain flow alignment and absence of porosity.</p>'
    ],
    [
        'title' => 'Industry 4.0: Smart Manufacturing in Modern Forging Plants',
        'slug' => 'industry-4-smart-manufacturing-forging-plants',
        'excerpt' => 'Digital transformation is revolutionizing the forging industry. Explore how IoT sensors, AI-driven analytics, and automation are creating smarter, more efficient forging operations.',
        'author' => 'JK Forge Team',
        'content' => '<h2>The Digital Forge</h2><p>Industry 4.0 is transforming traditional forging operations into connected, data-driven smart factories. By integrating sensors, analytics, and automation, forging companies can achieve unprecedented levels of quality, efficiency, and responsiveness.</p><h2>Key Technologies</h2><h3>IoT Sensors and Monitoring</h3><p>Modern forging presses are equipped with sensors that monitor:</p><ul><li>Press load and energy consumption per stroke</li><li>Die temperature distribution in real-time</li><li>Vibration patterns that indicate die wear or alignment issues</li><li>Cycle times and production rates</li></ul><h3>Predictive Maintenance</h3><p>By analyzing sensor data with machine learning algorithms, we can predict equipment failures before they occur. This proactive approach has reduced unplanned downtime by 60% and extended die life by 25% at leading forging facilities.</p><h3>Digital Twin Technology</h3><p>A digital twin is a virtual replica of the forging process that runs in parallel with the physical operation. Engineers can simulate process changes, optimize parameters, and predict quality outcomes without disrupting production.</p><h2>AI-Powered Quality Control</h2><p>Computer vision systems equipped with AI can inspect forged components at production speed, detecting surface defects as small as 0.1mm. These systems learn from historical data to improve detection accuracy over time, achieving defect detection rates exceeding 99.5%.</p><h3>Automated Material Handling</h3><p>Robotic systems now handle billet loading, part transfer between forging stations, and palletizing of finished components. This improves consistency, reduces cycle times, and enhances worker safety by removing operators from the immediate forging area.</p><blockquote>The integration of Industry 4.0 technologies has helped leading forging companies reduce scrap rates by 40%, improve energy efficiency by 25%, and increase overall equipment effectiveness (OEE) by 15-20%.</blockquote>'
    ]
];

$count = 0;
foreach ($posts as $i => $post) {
    // Check if slug already exists
    $stmt = blog_db_query("SELECT id FROM blog_posts WHERE slug = :slug", ['slug' => $post['slug']]);
    if ($stmt->fetch()) {
        echo "Skipping '{$post['title']}' (already exists)\n";
        continue;
    }

    // Stagger dates so posts aren't all the same day
    $daysAgo = ($i * 5) + 2; // 2, 7, 12, 17, ... days ago
    $createdAt = date('Y-m-d H:i:s', strtotime("-{$daysAgo} days"));

    blog_db_query(
        "INSERT INTO blog_posts (title, slug, excerpt, content, author, status, created_at, updated_at)
         VALUES (:title, :slug, :excerpt, :content, :author, 'published', :created_at, :created_at)",
        [
            'title' => $post['title'],
            'slug' => $post['slug'],
            'excerpt' => $post['excerpt'],
            'content' => $post['content'],
            'author' => $post['author'],
            'created_at' => $createdAt
        ]
    );
    $count++;
    echo "Created: {$post['title']}\n";
}

echo "\nDone! {$count} blog posts seeded.\n";
